# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper.rb"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  # config.filter_run :focus
end


require 'active_record'

# ActiveRecord.default_timezone = "Eastern Time (US & Canada)"
# config.time_zone = "Eastern Time (US & Canada)"

#Time.zone = "Eastern Time (US & Canada)"
#ActiveRecord::Base.time_zone_aware_attributes = true
#ActiveRecord::Base.default_timezone = "Eastern Time (US & Canada)"

ActiveRecord::Base.establish_connection(
 { :adapter => 'sqlite3', :database => File.dirname(__FILE__) + "/db/development.sqlite3" }
)

Dir[File.dirname(__FILE__) + '/sample_models/*.rb'].each do |file|
  require file
end
